"""Added PlaybackState

Revision ID: 0bc345f3e21a
Revises: 398d38290990
Create Date: 2026-10-02 16:16:29.012379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path

project_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_dir / "app"))

from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0bc345f3e21a'
down_revision: Union[str, Sequence[str], None] = '398d38290990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playback_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_states',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('position', sa.FLOAT(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.Column('paused_at', sa.VARCHAR(), nullable=True),
    sa.Column('shuffle_active', sa.BOOLEAN(), nullable=False),
    sa.Column('queue', sqlite.JSON(), nullable=False),
    sa.Column('loaded_songs', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
