"""add enabled to songs

Revision ID: 255fc618f594
Revises:
Create Date: 2026-07-19 04:30:28.745439

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "255fc618f594"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "songs",
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songs", "enabled")
    # ### end Alembic commands ###
