"""Added song copyright status

Revision ID: 398d38290990
Revises: d967ec0ab7ba
Create Date: 2026-07-19 14:52:26.550681

"""

import sys
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

project_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_dir / "app"))


# revision identifiers, used by Alembic.
revision: str = "398d38290990"
down_revision: Union[str, Sequence[str], None] = "d967ec0ab7ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "songs",
        sa.Column(
            "copyright_status",
            sa.Enum(
                "active",
                "copyright_claimed",
                name="songcopyrightstatus",
                native_enum=False,
            ),
            nullable=False,
            server_default="active",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songs", "copyright_status")
    # ### end Alembic commands ###
