"""initial schema

Revision ID: d967ec0ab7ba
Revises:
Create Date: 2026-07-19 14:51:35.128912

"""

import sys
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

project_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_dir / "app"))

import database.types

# revision identifiers, used by Alembic.
revision: str = "d967ec0ab7ba"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("custom_artwork", sa.String(), nullable=True),
        sa.Column("last_updated", database.types.UTCDateTime(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("setlist", "collection", name="albumtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("date", database.types.UTCDateTime(), nullable=True),
        sa.Column("disc", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "\n                (type = 'collection' AND disc IS NOT NULL) OR\n                (type = 'setlist' AND date IS NOT NULL)\n            ",
            name="ck_albums_vaild_type_data",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_album_type_date", "albums", ["type", "date"], unique=False)
    op.create_index("ix_album_type_disc", "albums", ["type", "disc"], unique=False)
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=True)
    op.create_table(
        "share_links",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("song", "playlist", name="sharelinktype", native_enum=False),
            nullable=False,
        ),
        sa.Column("external_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", database.types.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("link"),
    )
    op.create_table(
        "songs",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("title_original", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "original",
                "collab",
                "cover",
                "mashup",
                name="songtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("date_released", database.types.UTCDateTime(), nullable=False),
        sa.Column("disc", sa.Integer(), nullable=True),
        sa.Column("custom_artwork", sa.String(), nullable=True),
        sa.Column("is_copyrighted", sa.Boolean(), nullable=False),
        sa.Column("seconds", sa.Float(), nullable=False),
        sa.Column(
            "metadata_source",
            sa.Enum(
                "json",
                "id3",
                "manual",
                "youtube",
                name="metadatasource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_songs_type"), "songs", ["type"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="userroles", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "album_songs",
        sa.Column("album_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("album_id", "song_id"),
    )
    op.create_table(
        "identities",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "google", "discord", "legacy", name="authprovider", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_id", name="uq_auth_provider_identity"
        ),
    )
    op.create_table(
        "playlists",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("custom_artwork", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("user", "liked_songs", name="playlisttype", native_enum=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playlists_user_id"), "playlists", ["user_id"], unique=False
    )
    op.create_table(
        "song_artists",
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "artist_id"),
    )
    op.create_table(
        "song_audio_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "gdrive",
                "youtube",
                "manual",
                name="audioreferencetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("audio_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "external_id", name="uq_audio_type_external_id"),
    )
    op.create_index(
        "ix_audio_type_external_id",
        "song_audio_references",
        ["type", "external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_audio_references_audio_hash"),
        "song_audio_references",
        ["audio_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_audio_references_external_id"),
        "song_audio_references",
        ["external_id"],
        unique=False,
    )
    op.create_table(
        "song_singers",
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "artist_id"),
    )
    op.create_table(
        "legacy_creds",
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["identity_id"], ["identities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("identity_id"),
    )
    op.create_table(
        "playlist_songs",
        sa.Column("playlist_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("date_added", database.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "song_id"),
    )
    op.create_table(
        "tokens",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("identity_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", database.types.UTCDateTime(), nullable=False),
        sa.Column("secret_hash", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_created", database.types.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", database.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["identity_id"], ["identities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    op.drop_table("playlist_songs")
    op.drop_table("legacy_creds")
    op.drop_table("song_singers")
    op.drop_index(
        op.f("ix_song_audio_references_external_id"), table_name="song_audio_references"
    )
    op.drop_index(
        op.f("ix_song_audio_references_audio_hash"), table_name="song_audio_references"
    )
    op.drop_index("ix_audio_type_external_id", table_name="song_audio_references")
    op.drop_table("song_audio_references")
    op.drop_table("song_artists")
    op.drop_index(op.f("ix_playlists_user_id"), table_name="playlists")
    op.drop_table("playlists")
    op.drop_table("identities")
    op.drop_table("album_songs")
    op.drop_table("users")
    op.drop_index(op.f("ix_songs_type"), table_name="songs")
    op.drop_table("songs")
    op.drop_table("share_links")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_table("artists")
    op.drop_index("ix_album_type_disc", table_name="albums")
    op.drop_index("ix_album_type_date", table_name="albums")
    op.drop_table("albums")
    # ### end Alembic commands ###
